import { Toaster } from "sonner"
import "./globals.css"
import Navbar from "./components/navbar"
import SessionProviderWrapper from "./components/SessionProviderWrapper"
import Footer from "./components/footer"
import Providers from "./providers"


export const metadata = {
  title: "Electronics E-Commerce | Website",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>
          <Navbar />
          <Providers>
            <main className="pt-20">
              {children}
              <Toaster
                position="top-right"
                richColors
                closeButton
              />
            </main>
          </Providers>
        </SessionProviderWrapper>
        <Footer />
      </body>
    </html>
  )
}
