import { Toaster } from "sonner"
import "./globals.css"
import SessionProviderWrapper from "./components/SessionProviderWrapper"
import Providers from "./providers"
import localFont from "next/font/local";

const inter = localFont({
  src: [
    {
      path: "../../public/fonts/Inter-VariableFont_opsz,wght.ttf",
      style: "normal",
    },
    {
      path: "../../public/fonts/Inter-Italic-VariableFont_opsz,wght.ttf",
      style: "italic",
    },
  ],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Ai Powered Resume Builder Website - In One Minute",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <SessionProviderWrapper>
          <Providers>
              {children}
              <Toaster
              position="top-center"/>
          </Providers>
        </SessionProviderWrapper>
      </body>
    </html>
  )
}
